image: node:14.0.0
pipelines:
  branches:
    master:
      - step:
          name: Build Staging
          caches:
            - node
          script:
            - unset CI
            - npm install
            - npm start&
            - npm run build:staging
          artifacts:
            - build/**
      - step:
          name: Deploy to Staging
          deployment: Staging
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: ${EC2_USER}
                SERVER: ${EC2_IP}
                REMOTE_PATH: ${REMOTE_PATH}
                LOCAL_PATH: 'build/*'
                DEBUG: "true"
      - step:
          name: Build Production
          caches:
            - node
          script:
            - unset CI
            - npm install
            #- npm start&
            - npm run build:production
          artifacts:
            - build/**
      - step:
          name: Deploy to Production
          trigger: manual
          deployment: Production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: ${EC2_USER}
                SERVER: ${EC2_IP}
                REMOTE_PATH: ${REMOTE_PATH}
                LOCAL_PATH: 'build/*'
                DEBUG: "true"